apiVersion: v1
kind: Service
metadata: {name: sample-service, namespace: marketflow-local, labels: {app.kubernetes.io/part-of: marketflow}}
spec: {selector: {app.kubernetes.io/name: sample-service}, ports: [{name: http, port: 8080, targetPort: http}], type: ClusterIP}
---
apiVersion: v1
kind: Service
metadata: {name: identity-service, namespace: marketflow-local, labels: {app.kubernetes.io/part-of: marketflow}}
spec: {selector: {app.kubernetes.io/name: identity-service}, ports: [{name: http, port: 8081, targetPort: http}], type: ClusterIP}
---
apiVersion: v1
kind: Service
metadata: {name: seller-service, namespace: marketflow-local, labels: {app.kubernetes.io/part-of: marketflow}}
spec: {selector: {app.kubernetes.io/name: seller-service}, ports: [{name: http, port: 8082, targetPort: http}], type: ClusterIP}
---
apiVersion: v1
kind: Service
metadata: {name: catalog-service, namespace: marketflow-local, labels: {app.kubernetes.io/part-of: marketflow}}
spec: {selector: {app.kubernetes.io/name: catalog-service}, ports: [{name: http, port: 8083, targetPort: http}], type: ClusterIP}
---
apiVersion: v1
kind: Service
metadata: {name: inventory-service, namespace: marketflow-local, labels: {app.kubernetes.io/part-of: marketflow}}
spec: {selector: {app.kubernetes.io/name: inventory-service}, ports: [{name: http, port: 8084, targetPort: http}], type: ClusterIP}
---
apiVersion: v1
kind: Service
metadata: {name: search-service, namespace: marketflow-local, labels: {app.kubernetes.io/part-of: marketflow}}
spec: {selector: {app.kubernetes.io/name: search-service}, ports: [{name: http, port: 8085, targetPort: http}], type: ClusterIP}
---
apiVersion: v1
kind: Service
metadata: {name: cart-service, namespace: marketflow-local, labels: {app.kubernetes.io/part-of: marketflow}}
spec: {selector: {app.kubernetes.io/name: cart-service}, ports: [{name: http, port: 8086, targetPort: http}], type: ClusterIP}
---
apiVersion: v1
kind: Service
metadata: {name: order-service, namespace: marketflow-local, labels: {app.kubernetes.io/part-of: marketflow}}
spec: {selector: {app.kubernetes.io/name: order-service}, ports: [{name: http, port: 8087, targetPort: http}], type: ClusterIP}
---
apiVersion: v1
kind: Service
metadata: {name: payment-service, namespace: marketflow-local, labels: {app.kubernetes.io/part-of: marketflow}}
spec: {selector: {app.kubernetes.io/name: payment-service}, ports: [{name: http, port: 8088, targetPort: http}], type: ClusterIP}
---
apiVersion: v1
kind: Service
metadata: {name: notification-service, namespace: marketflow-local, labels: {app.kubernetes.io/part-of: marketflow}}
spec: {selector: {app.kubernetes.io/name: notification-service}, ports: [{name: http, port: 8089, targetPort: http}], type: ClusterIP}
