apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "marketflow.fullname" . }}-runtime
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "marketflow.labels" . | nindent 4 }}
data:
  MARKETFLOW_ENVIRONMENT: {{ .Values.environment | quote }}
  MARKETFLOW_DEPLOYMENT_PROFILE: free-local
  IDENTITY_TOKEN_AUDIENCE: marketflow-api
  IDENTITY_TOKEN_ISSUER: http://identity-service:8081
  IDENTITY_BASE_URL: http://identity-service:8081
  SELLER_BASE_URL: http://seller-service:8082
  CATALOG_BASE_URL: http://catalog-service:8083
  INVENTORY_BASE_URL: http://inventory-service:8084
  SEARCH_BASE_URL: http://search-service:8085
  CART_BASE_URL: http://cart-service:8086
  ORDER_BASE_URL: http://order-service:8087
  PAYMENT_BASE_URL: http://payment-service:8088
  NOTIFICATION_BASE_URL: http://notification-service:8089
  IDENTITY_DATABASE_URL: jdbc:postgresql://{{ .Values.external.postgresHost }}:5432/marketflow_identity
  SELLER_DATABASE_URL: jdbc:postgresql://{{ .Values.external.postgresHost }}:5432/marketflow_seller
  CATALOG_DATABASE_URL: jdbc:postgresql://{{ .Values.external.postgresHost }}:5432/marketflow_catalog
  INVENTORY_DATABASE_URL: jdbc:postgresql://{{ .Values.external.postgresHost }}:5432/marketflow_inventory
  SEARCH_DATABASE_URL: jdbc:postgresql://{{ .Values.external.postgresHost }}:5432/marketflow_search
  ORDER_DATABASE_URL: jdbc:postgresql://{{ .Values.external.postgresHost }}:5432/marketflow_order
  PAYMENT_DATABASE_URL: jdbc:postgresql://{{ .Values.external.postgresHost }}:5432/marketflow_payment
  NOTIFICATION_DATABASE_URL: jdbc:postgresql://{{ .Values.external.postgresHost }}:5432/marketflow_notification
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.external.kafkaBootstrapServers | quote }}
  RABBITMQ_ADDRESSES: {{ .Values.external.rabbitmqAddresses | quote }}
  REDIS_HOST: {{ .Values.external.redisHost | quote }}
  OPENSEARCH_URL: {{ .Values.external.opensearchUrl | quote }}
  OBJECT_STORAGE_ENDPOINT: {{ .Values.external.objectStorageEndpoint | quote }}
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: {{ .Values.external.otlpEndpoint | quote }}
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "0.10"
