apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "marketflow.labels" . | nindent 4 }}
  annotations:
    marketflow.io/secret-source: external-secret-or-local-operator
type: Opaque
stringData: {}
